name: x64-linux
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    if: >-
      !(
        contains(github.event.head_commit.message, '[ci skip]') ||
        contains(github.event.head_commit.message, '[skip ci]') ||
        contains(github.event.head_commit.message, '[actions skip]') ||
        contains(github.event.head_commit.message, '[skip actions]')
      )
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install dependencies
      run: |
        sudo apt-get --no-install-recommends --yes install libasio-dev libboost-date-time-dev libboost-filesystem-dev \
        libboost-dev libfmt-dev libgit2-dev libspdlog-dev libsqlite3-dev meson ninja-build nlohmann-json3-dev
    - name: Meson build
      run: |
        CC=clang CXX=clang++ meson setup build
        cd build
        ninja
