name: x64-linux
on: push
jobs:
  x64-linux:
    runs-on: ubuntu-24.04
    if: >-
      !(
        contains(github.event.head_commit.message, '[ci skip]') ||
        contains(github.event.head_commit.message, '[skip ci]') ||
        contains(github.event.head_commit.message, '[actions skip]') ||
        contains(github.event.head_commit.message, '[skip actions]')
      )
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install dependencies
      run: |
        sudo apt-get --no-install-recommends --yes install libfmt-dev libgit2-dev libsqlite3-dev libssl-dev libboost-all-dev ninja-build
        pip install meson
    - name: Meson build
      run: |
        export CC=clang
        export CXX=clang++
        meson setup build -Dwarning_level=3
        meson compile -C build -j2
