name: x64-osx
on: push
jobs:
  build:
    runs-on: macos-latest
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.11
      SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install 10.11 SDK
        run: |
          curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name \
            https://raw.githubusercontent.com/edo9300/ygopro/master/travis/get-osx-sdk.sh
          chmod +x get-osx-sdk.sh
          ./get-osx-sdk.sh $MACOSX_DEPLOYMENT_TARGET
      - name: Install Homebrew prerequisites
        run: |
          brew update
          brew install p7zip
      - name: Fetch cached vcpkg dependencies
        run: |
          mkdir vcpkg
          cd vcpkg
          curl --retry 5 --connect-timeout 30 --location --remote-header-name --output installed.7z \
            https://github.com/kevinlul/edopro-vcpkg-cache/releases/download/latest/igmr_x64-osx.7z
          7z x installed.7z
      - name: CMake build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build . --config Debug --parallel 2
