name: x86-windows
on: push
jobs:
  x86-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Setup msys2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: mingw32
        install: mingw-w64-i686-toolchain make mingw-w64-i686-libgit2-winhttp mingw-w64-i686-fmt mingw-w64-i686-boost mingw-w64-i686-sqlite3 mingw-w64-i686-openssl pkgconf mingw-w64-i686-meson
    - name: Meson build
      shell: msys2 {0}
      run: |
        LDFLAGS="-static-libstdc++ -static-libgcc -static" meson setup build -Dbuildtype=release -Dstrip=true -Db_lto=true -Db_ndebug=true
        meson compile -C build -j$(nproc)
    - name: Setup directory with artifacts
      shell: bash
      run: |
        export RDIR=Multirole
        mkdir $RDIR
        cp build/hornet.exe $RDIR/
        cp build/multirole.exe $RDIR/
        cp etc/config.json $RDIR/
        sed -i "s/libocgcore\\\\\\\.so/ocgcore\\\\\\\.dll/g" $RDIR/config.json
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Multirole
        path: Multirole/
