name: x86-windows-static
on: push
jobs:
  build:
    runs-on: windows-latest
    if: >-
      !(
        contains(github.event.head_commit.message, '[ci skip]') ||
        contains(github.event.head_commit.message, '[skip ci]') ||
        contains(github.event.head_commit.message, '[actions skip]') ||
        contains(github.event.head_commit.message, '[skip actions]')
      )
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Fetch cached vcpkg dependencies
      shell: bash
      run: |
        mkdir vcpkg
        cd vcpkg
        curl --retry 5 --connect-timeout 30 --location --remote-header-name --output installed.7z \
          https://github.com/kevinlul/edopro-vcpkg-cache/releases/download/latest/igmr_x86-windows-static.7z
        "$PROGRAMFILES/7-Zip/7z.exe" x installed.7z
        ./vcpkg.exe integrate install
    - name: CMake build
      shell: bash
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake \
          -DVCPKG_TARGET_TRIPLET=x86-windows-static -DCMAKE_GENERATOR_PLATFORM=Win32
        cmake --build . --config Debug --parallel 2
